# Generated by Django 5.1.7 on 2025-06-05 21:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(help_text='Ejemplo: S00101', max_length=20, unique=True, verbose_name='Número de Cotización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('salesperson_name', models.CharField(default='Elias Gil', max_length=100, verbose_name='Vendedor')),
                ('quotation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Cotización')),
                ('expiration_date', models.DateField(verbose_name='Fecha de Expiración')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('expired', 'Expirada')], default='draft', max_length=20, verbose_name='Estado')),
                ('payment_terms', models.TextField(default='Anticipo del 60% para la programación de los trabajos.\nSaldo del 40% al término de los mismos.', verbose_name='Términos de Pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('company_name', models.CharField(default='Total Garden & Pool', max_length=200, verbose_name='Nombre de la Empresa')),
                ('company_address', models.TextField(default='Calle 9 No. 167 x 16 y 18\nColonia. Mulsay CP. 97249\nMérida Yucatán\nMéxico.', verbose_name='Dirección de la Empresa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-quotation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de Impuesto (%)')),
                ('description', models.TextField(blank=True, help_text='Deja en blanco para usar la descripción del servicio', verbose_name='Descripción Personalizada')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation', verbose_name='Cotización')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Item de Cotización',
                'verbose_name_plural': 'Items de Cotización',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
