# Generated by Django 5.2.2 on 2025-06-05 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_salesperson'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='salesperson_name',
        ),
        migrations.AddField(
            model_name='quotation',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='core.salesperson', verbose_name='Vendedor'),
        ),
    ]
