# Generated by Django 5.1.7 on 2025-06-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_remove_quotation_salesperson_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='terms_and_conditions',
            field=models.TextField(blank=True, help_text='Se llenarán automáticamente desde el perfil de la empresa', verbose_name='Términos y Condiciones'),
        ),
    ]
