# Generated by Django 5.1.7 on 2025-06-05 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_quotation_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='custom_image',
            field=models.ImageField(blank=True, help_text='Imagen específica para esta cotización (opcional, usa la del servicio si está vacía)', null=True, upload_to='quotations/items/', verbose_name='Imagen Personalizada'),
        ),
        migrations.CreateModel(
            name='QuotationItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quotations/items/gallery/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, help_text='Descripción de la imagen', max_length=200, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='quotations.quotationitem', verbose_name='Item de Cotización')),
            ],
            options={
                'verbose_name': 'Imagen Adicional de Item',
                'verbose_name_plural': 'Imágenes Adicionales de Items',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
