# Generated by Django 5.1.7 on 2025-06-05 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_quotationitem_custom_image_quotationitemimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-quotation_date', '-created_at'], 'verbose_name': 'Cotizacion', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='quotationitem',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Item de Cotizacion', 'verbose_name_plural': 'Items de Cotizacion'},
        ),
        migrations.AlterModelOptions(
            name='quotationitemimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Imagen Adicional de Item', 'verbose_name_plural': 'Imagenes Adicionales de Items'},
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='custom_image',
            field=models.ImageField(blank=True, help_text='Imagen especifica para esta cotizacion (opcional, usa la del servicio si esta vacia)', null=True, upload_to='quotations/items/', verbose_name='Imagen Personalizada'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='description',
            field=models.TextField(blank=True, help_text='Deja en blanco para usar la descripcion del servicio', verbose_name='Descripcion Personalizada'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation', verbose_name='Cotizacion'),
        ),
        migrations.AlterField(
            model_name='quotationitemimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Descripcion de la imagen', max_length=200, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='quotationitemimage',
            name='quotation_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='quotations.quotationitem', verbose_name='Item de Cotizacion'),
        ),
    ]
