# Generated by Django 5.2.2 on 2025-06-06 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_quotationphotographicreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('status_change', 'Cambio de Estado'), ('created', 'Cotización Creada'), ('updated', 'Cotización Actualizada'), ('item_added', 'Servicio Agregado'), ('item_removed', 'Servicio Eliminado'), ('item_updated', 'Servicio Modificado'), ('note', 'Nota'), ('call_made', 'Llamada Realizada'), ('call_received', 'Llamada Recibida'), ('email_sent', 'Email Enviado'), ('email_received', 'Email Recibido'), ('meeting_scheduled', 'Reunión Programada'), ('meeting_completed', 'Reunión Realizada'), ('document_sent', 'Documento Enviado'), ('payment_received', 'Pago Recibido'), ('visit_scheduled', 'Visita Programada'), ('visit_completed', 'Visita Realizada'), ('follow_up', 'Seguimiento'), ('reminder', 'Recordatorio'), ('other', 'Otro')], max_length=30, verbose_name='Tipo de Actividad')),
                ('title', models.CharField(help_text='Título breve de la actividad', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción detallada de la actividad', verbose_name='Descripción')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Estado Anterior')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='Estado Nuevo')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Programada')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Completada')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridad')),
                ('requires_follow_up', models.BooleanField(default=False, verbose_name='Requiere Seguimiento')),
                ('follow_up_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Seguimiento')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Persona de Contacto')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('additional_data', models.JSONField(blank=True, help_text='Información adicional en formato JSON', null=True, verbose_name='Datos Adicionales')),
                ('is_automatic', models.BooleanField(default=False, help_text='Indica si la actividad fue generada automáticamente por el sistema', verbose_name='Automático')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='quotations.quotation', verbose_name='Cotización')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Actividad de Cotización',
                'verbose_name_plural': 'Actividades de Cotización',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['quotation', '-created_at'], name='quotations__quotati_b7d362_idx'), models.Index(fields=['activity_type', '-created_at'], name='quotations__activit_e2415a_idx'), models.Index(fields=['requires_follow_up', 'follow_up_date'], name='quotations__require_3b38c5_idx')],
            },
        ),
    ]
