# Generated by Django 5.2.2 on 2025-06-22 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_companyprofile_options_and_more'),
        ('quotations', '0008_quotation_company_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='salesperson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='core.salesperson', verbose_name='Vendedor'),
            preserve_default=False,
        ),
    ]
