# Generated by Django 5.1.7 on 2025-06-05 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Imagen principal que aparecerá en las cotizaciones', null=True, upload_to='services/images/', verbose_name='Imagen Principal'),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, help_text='Descripción opcional de la imagen', max_length=200, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la galería', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='services.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Imagen de Servicio',
                'verbose_name_plural': 'Imágenes de Servicios',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
