# Generated by Django 5.1.7 on 2025-06-05 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_main_image_serviceimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['name'], 'verbose_name': 'Categoria de Servicio', 'verbose_name_plural': 'Categorias de Servicios'},
        ),
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Imagen de Servicio', 'verbose_name_plural': 'Imagenes de Servicios'},
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicecategory', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Descripcion opcional de la imagen', max_length=200, verbose_name='Descripcion'),
        ),
    ]
