# Generated by Django 5.2.2 on 2025-06-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'ordering': ('order',), 'verbose_name': 'Imagen de Servicio', 'verbose_name_plural': 'Imagenes de Servicios'},
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
