# Generated by Django 5.1.7 on 2025-06-05 21:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=16.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tasa de Impuesto por Defecto (%)')),
                ('default_payment_terms', models.TextField(default='Anticipo del 60% para la programación de los trabajos.\nSaldo del 40% al término de los mismos.', verbose_name='Términos de Pago por Defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Perfil de la Empresa',
                'verbose_name_plural': 'Perfiles de la Empresa',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_validity_days', models.PositiveIntegerField(default=7, verbose_name='Días de Validez de Cotización')),
                ('quotation_number_prefix', models.CharField(default='S', max_length=5, verbose_name='Prefijo del Número de Cotización')),
                ('currency_symbol', models.CharField(default='$', max_length=5, verbose_name='Símbolo de Moneda')),
                ('currency_code', models.CharField(default='MXN', max_length=3, verbose_name='Código de Moneda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
