# Generated by Django 5.2.2 on 2025-06-05 22:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Formato: +999999999. Hasta 15 dígitos permitidos.', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('employee_id', models.CharField(blank=True, help_text='Código único del empleado', max_length=20, unique=True, verbose_name='ID Empleado')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Contratación')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de comisión sobre ventas', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tasa de Comisión (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
