# Generated by Django 5.1.7 on 2025-06-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_salesperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='terms_and_conditions',
            field=models.TextField(blank=True, default='1. Orders and Payments\nESTOS PRECIOS NO INCLUYEN IVA.\nEn caso de requerir facturase incrementa el 16% correspondiente.\nCada cotización tendrá su especificaciones de métodos y porcentajes de pago.\n\n2. Product Descriptions\nLAS FOTOS EN ESTE PRESUPUESTO SON ILUSTRATIVAS SEMEJANDO EL PRODUCTO COTIZADO.\n\n3. Shipping and Delivery\nTIEMPO DE ENTREGA 7 DÍAS HÁBILES.\nEN CASO DE DESASTRE NATURAL SE VOLVERÁ A CONFIRMAR EL TIEMPO DE ENTREGA\n\n4. WARRANTY.\nSE OTORGA GARANTÍA EN PASTO POR 30 DÍAS.\nSE OTORGA GARANTÍA EN PLANTAS POR 60 DÍAS.\nSE OTORGA GARANTÍA EN ÁRBOLES POR 6 MESES.\nAPLICA GARANTÍA MENCIONADA SI Y SOLO SI SE CONTRATAN LOS SERVICIOS DE SISTEMA DE RIEGO AUTOMÁTICO.\nNO APLICA EN CASO DE FALLO DE LUZ ELÉCTRICA PROPORCIONADA POR CLIENTE. NO APLICA EN CASO DE DESASTRE NATURAL.', help_text='Términos y condiciones detallados que aparecerán en las cotizaciones', verbose_name='Términos y Condiciones Completos'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
    ]
