# Generated by Django 5.2.2 on 2025-06-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companyprofile_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Foto del vendedor para mostrar en cotizaciones', null=True, upload_to='salespersons/', verbose_name='Foto de Perfil'),
        ),
    ]
