# Generated by Django 5.2.2 on 2025-06-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_salesperson_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'ordering': ['name'], 'verbose_name': 'Perfil de la Empresa', 'verbose_name_plural': 'Perfiles de la Empresa'},
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='is_active',
        ),
    ]
