# Generated by Django 5.2.2 on 2025-06-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_companyprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='default_email_from',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de Envío por Defecto'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_notifications',
            field=models.BooleanField(default=True, verbose_name='Habilitar Notificaciones'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='primary_color',
            field=models.CharField(choices=[('primary', 'Azul (Predeterminado)'), ('success', 'Verde'), ('info', 'Cian'), ('warning', 'Amarillo'), ('danger', 'Rojo'), ('dark', 'Negro'), ('purple', 'Morado'), ('pink', 'Rosa'), ('orange', 'Naranja'), ('teal', 'Verde Azulado'), ('indigo', 'Índigo')], default='primary', max_length=20, verbose_name='Color Principal de la Plataforma'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='system_name',
            field=models.CharField(default='Quotify', max_length=100, verbose_name='Nombre del Sistema'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='quotation_number_prefix',
            field=models.CharField(default='S', max_length=10, verbose_name='Prefijo del Número de Cotización'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
    ]
