# Generated by Django 5.2.2 on 2025-07-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_expand_system_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Imagen principal que aparecerá en la portada de las cotizaciones', null=True, upload_to='company/covers/', verbose_name='Imagen de Portada'),
        ),
    ]
