# Generated by Django 5.2.2 on 2025-07-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_cover_image_to_company_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='slogan',
            field=models.CharField(blank=True, help_text="Slogan que aparecerá en la portada de las cotizaciones (ej: 'NUESTRO COMPROMISO: SU JARDÍN')", max_length=200, verbose_name='Slogan de la Empresa'),
        ),
    ]
