# Generated by Django 5.2.2 on 2025-07-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_slogan_to_company_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='brand_color',
            field=models.CharField(choices=[('#2c5f2d', 'Verde (Predeterminado)'), ('#1e3a8a', 'Azul'), ('#7c3aed', 'Morado'), ('#dc2626', 'Rojo'), ('#ea580c', 'Naranja'), ('#0891b2', 'Cian'), ('#059669', 'Esmeralda'), ('#7c2d12', 'Café'), ('#374151', 'Gris'), ('#be123c', 'Rosa'), ('#4338ca', 'Índigo'), ('#a21caf', 'Fucsia')], default='#2c5f2d', help_text='Color principal que se utilizará en las cotizaciones de esta empresa', max_length=7, verbose_name='Color de la Empresa'),
        ),
    ]
