# Generated by Django 5.2.2 on 2025-06-25 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('note_type', models.CharField(choices=[('general', 'General'), ('follow_up', 'Seguimiento'), ('complaint', 'Queja'), ('compliment', 'Elogio'), ('payment', 'Pago'), ('technical', 'Técnica'), ('commercial', 'Comercial')], default='general', max_length=20, verbose_name='Tipo de nota')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('is_private', models.BooleanField(default=False, help_text='Solo visible para el autor', verbose_name='Nota privada')),
                ('is_resolved', models.BooleanField(default=False, help_text='Marcar si la nota ha sido resuelta o atendida', verbose_name='Resuelto')),
                ('follow_up_date', models.DateField(blank=True, help_text='Fecha para dar seguimiento a esta nota', null=True, verbose_name='Fecha de seguimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Nota del Cliente',
                'verbose_name_plural': 'Notas de Clientes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='clients_cli_client__b25648_idx'), models.Index(fields=['priority', 'is_resolved'], name='clients_cli_priorit_6ee654_idx'), models.Index(fields=['follow_up_date'], name='clients_cli_follow__9d4ce1_idx')],
            },
        ),
    ]
